parameters:
- name: publish
  type: boolean
  default: false
- name: artifactFeed
  type: string
- name: cibuildwheelPythonUrl
  type: string

jobs:
- job: BuildWindows
  displayName: 'Build Windows Wheels'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: ${{ parameters.artifactFeed }}
  
  - script: |
      python -m pip install --upgrade pip
      pip install cibuildwheel
    displayName: 'Install build dependencies'
  
  - script: |
      cibuildwheel --output-dir wheel-win-x64
    displayName: 'Build win-x64 wheels'
    env:
      CIBW_ARCHS_WINDOWS: "AMD64"
      CIBW_ENVIRONMENT: "ARTIFACTS_CREDENTIAL_PROVIDER_RID=win-x64"
      CIBW_CPYTHON_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}
      CIBW_PYPY_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}
  
  - ${{ if eq(parameters.publish, true) }}:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish win-x64 wheels'
      inputs:
        pathToPublish: 'wheel-win-x64'
        artifactName: 'wheels-win-x64'

- job: BuildOSX
  displayName: 'Build macOS Wheels'
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: ${{ parameters.artifactFeed }}
  
  - script: |
      python3 -m pip install --upgrade pip
      # Work around for https://github.com/pypa/cibuildwheel/issues/2649
      pip install cibuildwheel --only-binary patchelf
    displayName: 'Install build dependencies'
  
  - script: |
      cibuildwheel --output-dir wheel-osx-x64
    displayName: 'Build osx-x64 wheels'
    env:
      CIBW_ARCHS_MACOS: "x86_64"
      CIBW_ENVIRONMENT: "ARTIFACTS_CREDENTIAL_PROVIDER_RID=osx-x64"
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      CIBW_CPYTHON_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}
      CIBW_PYPY_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}

  - script: |
      cibuildwheel --output-dir wheel-osx-arm64
    displayName: 'Build osx-arm64 wheels'
    env:
      CIBW_ARCHS_MACOS: "arm64"
      CIBW_ENVIRONMENT: "ARTIFACTS_CREDENTIAL_PROVIDER_RID=osx-arm64"
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      CIBW_CPYTHON_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}
      CIBW_PYPY_STANDALONE_URL: ${{ parameters.cibuildwheelPythonUrl }}
  
  - ${{ if eq(parameters.publish, true) }}:
    - task: PublishBuildArtifacts@1
      displayName: 'Publish osx-x64 wheels'
      inputs:
        pathToPublish: 'wheel-osx-x64'
        artifactName: 'wheels-osx-x64'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish osx-arm64 wheels'
      inputs:
        pathToPublish: 'wheel-osx-arm64'
        artifactName: 'wheels-osx-arm64'

- job: BuildSDist
  displayName: 'Build Source Distribution'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: ${{ parameters.artifactFeed }}
  
  - script: |
      python -m pip install --upgrade pip build
      pip install setuptools
      pip install wheel
      pip install cibuildwheel
    displayName: 'Install build tools'
  
  - script: |
      python -m build --sdist
    displayName: 'Build source distribution'
    env:
      ARTIFACTS_CREDENTIAL_PROVIDER_NON_SC: "true"
  
  - ${{ if eq(parameters.publish, true) }}:
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'dist'
        artifactName: 'sdist'