schedules:
- cron: "0 0 * * SAT"
  displayName: CodeQL Saturday midnight (UTC) scan
  always: true
  branches:
    include: 
    - master

resources:
- repo: self

pool:
  vmImage: windows-latest

stages:
- stage: Build
  dependsOn: [] 
  jobs:
  - job: build
    steps:
    - template: build.yml
      parameters:
        publish: true

- stage: Validate
  dependsOn: [] 
  jobs:
  - template: validate-setup.yml
