schedules:
- cron: "0 0 * * SAT"
  displayName: CodeQL Saturday midnight (UTC) scan
  always: true
  branches:
    include: 
    - master

resources:
- repo: self

stages:
- stage: BuildWheels
  displayName: 'Build Platform-Specific Wheels'
  dependsOn: []
  jobs:
  - template: build-wheels.yml
    parameters:
      publish: true
      artifactFeed: 'PipelineTools/artifacts-credprovider'
      cibuildwheelPythonUrl: 'https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/artifacts-credprovider/pypi/simple/'

- stage: Validate
  displayName: 'Validate Setup Binary Selection'
  dependsOn: [] 
  jobs:
  - template: validate-setup.yml
    parameters:
      artifactFeed: 'Azure Artifacts/Azure-Artifacts'
