
resources:
- repo: self

pool:
  vmImage: windows-latest

trigger:
- master

stages:
- stage: Build
  dependsOn: []
  jobs:
  - job: build
    steps:
    - template: build.yml
      parameters:
        publish: false

- stage: Validate
  dependsOn: []
  jobs:
  - template: build/validate-setup.yml
