schedules:
- cron: "0 0 * * SAT"
  displayName: Saturday midnight (UTC) run
  always: true
  branches:
    include: 
    - master

resources:
- repo: self

pool:
  vmImage: windows-latest

pr:
  branches:
    include:
    - master
    - releases/*

stages:
- stage: BuildWheels
  displayName: 'Build Platform-Specific Wheels'
  dependsOn: []
  jobs:
  - template: build-wheels.yml
    parameters:
      publish: false # Enable this to publish wheels to the build artifacts for validation
      artifactFeed: PublicBuilds/artifacts-credprovider
      cibuildwheelPythonUrl: https://pkgs.dev.azure.com/artifacts-public/PublicBuilds/_packaging/artifacts-credprovider/pypi/simple/

- stage: Validate
  displayName: 'Validate Setup Binary Selection'
  dependsOn: [] 
  jobs:
  - template: validate-setup.yml
    parameters:
      artifactFeed: PublicBuilds/artifacts-credprovider
